habit_tracker/urls.py
from django.urls import path
from . import views

app_name = "habit_tracker"
urlpatterns = [
    path('', views.index, name="index"),
    path('track/<str:habit>', views.track_habit, name="track_habit"),
    path('add/', views.add_habit_entry, name="add_habit_entry"),
]

study_plan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('habits/', include("habit_tracker.urls")),
]

habit_tracker/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Habit(models.Model):
    name = models.CharField(max_length=40, default="Unnamed Habit")
    date = models.DateField(default=timezone.now)
    duration = models.IntegerField()

habit_tracker/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Max
from django.urls import reverse
from datetime import datetime
from .models import Habit
from . import util
import json

# Create your views here.
def index(request):
    return render(request, "habit_tracker/index.html", {
        "habits": util.list_habits()
    })


def track_habit(request, habit):
    # POST request
    if request.method == "POST":
        # TODO
        data = json.loads(request.body)
        date = data.get('habitDate')
        new_duration = data.get('habitDuration')

        edited_habit = Habit.objects.filter(name=habit, date=date).first()
        edited_habit.duration = new_duration
        edited_habit.save()

        entries = Habit.objects.filter(name=habit)
        max_duration = entries.aggregate(Max('duration'))['duration__max'] or 1
        data = util.update_data(entries, max_duration)

        return JsonResponse({
            'success': True,
            'message': 'Habit updated successfully.',
            'entries': data
        })

    # DELETE request
    elif request.method == "DELETE":
        # TODO
        data = json.loads(request.body)
        date = data.get('habitDate')

        edited_habit = Habit.objects.filter(name=habit, date=date).first()
        edited_habit.duration = 0
        edited_habit.save()

        entries = Habit.objects.filter(name=habit)
        max_duration = entries.aggregate(Max('duration'))['duration__max'] or 1
        data = util.update_data(entries, max_duration)

        return JsonResponse({
            'success': True,
            'message': 'Habit updated successfully.',
            'entries': data
        })

    # GET request
    else:
        entries = Habit.objects.filter(name=habit)
        max_duration = entries.aggregate(Max('duration'))['duration__max'] or 1

        data = util.update_data(entries, max_duration)

        return render(request, "habit_tracker/track.html", {
            "habit": habit,
            "entries": data,
            "weekdays": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        })


def add_habit_entry(request):
    if request.method == "POST":
        name = request.POST.get("name")
        date = request.POST.get("date")
        duration = request.POST.get("duration")

        if name not in util.list_habits():
            util.create_calendar(name, 2024)

        if not date:
            date = datetime.now().date()

        habit = Habit.objects.filter(name=name, date=date).first()

        if habit:
            habit.duration = habit.duration + int(duration)
            habit.save()

        else:
            habit = Habit(name=name, date=date, duration=duration)
            habit.save()

        return redirect("habit_tracker:track_habit", habit.name)

    else:
        return render(request, "habit_tracker/add.html")

habit_tracker/templates/habit_tracker/add.html
{% extends 'habit_tracker/layout.html' %}

{% block title %}
    <title>Add Habit</title>
{% endblock %}

{% block body %}
    <h1>Create New Habit</h1>

    <div class="ml-3 mt-5 entry">
        <form action="{% url 'habit_tracker:add_habit_entry' %}" method="post">
            {% csrf_token %}
            <div class="row mb-3">
                <input id="habit-name" type="text" name="name" placeholder="Name">
            </div>
            <div class="row mb-3">
                <input id="habit-date" type="date" name="date" placeholder="Date">
            </div>
            <div class="row mb-3">
                <input id="habitduration" type="number" name="duration" placeholder="Duration">
            </div>
            <div class="row mb-3">
                <input type="submit" value="Save">
            </div>
        </form>
    </div>
{% endblock %}

habit_tracker/templates/habit_tracker/index.html
{% extends 'habit_tracker/layout.html' %}

{% block title %}
    <title>Habit Tracker</title>
{% endblock %}

{% block body %}
    <h1>Habits</h1>
    <div>
        <ul>
            {% for habit in habits %}
                <li>
                    <a href="{% url 'habit_tracker:track_habit' habit %}">{{ habit }}</a>
                </li>
            {% endfor %}
        </ul>  
    </div>
{% endblock %}

habit_tracker/templates/habit_tracker/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}{% endblock %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'habit_tracker/css/styles.css' %}">
        <script src="{% static 'habit_tracker/js/index.js' %}"></script>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

habit_tracker/templates/habit_tracker/track.html
{% extends 'habit_tracker/layout.html' %}

{% block title %}
    <title>Habit Tracker</title>
{% endblock %}

{% block body %}
    <div id="habit">
        <h1>{{ habit }}</h1>
    </div>

    <div class="table-container scroll">
        <table>
            <thead>
                <tr>
                    <td></td>
                    <th colspan="4" class="months heading">Jan</th>
                    <th colspan="4" class="months heading">Feb</th>
                    <th colspan="5" class="months heading">March</th>
                    <th colspan="4" class="months heading">April</th>
                    <th colspan="4" class="months heading">May</th>
                    <th colspan="5" class="months heading">June</th>
                    <th colspan="4" class="months heading">July</th>
                    <th colspan="5" class="months heading">Aug</th>
                    <th colspan="4" class="months heading">Sept</th>
                    <th colspan="4" class="months heading">Oct</th>
                    <th colspan="5" class="months heading">Nov</th>
                    <th colspan="4" class="months heading">Dec</th>
                </tr>
            </thead>

            <tbody>
                {% for day in weekdays %}
                    <tr>
                        <th class="days heading">{{ day }}</th>

                        {% for entry in entries %}
                            {% if entry.date|date:'l' == day %}
                                <td>
                                    <div class="day" data-name="{{ entry.name }}" data-date="{{ entry.date|date:'Y-m-d' }}" data-duration="{{ entry.duration }}">
                                        <div class="day-inner" style="background-color: rgb(240, 94, 155, {{ entry.intensity }});"></div>

                                        <div class="container" id="tooltip">
                                            <div class="row mx-auto">
                                                <span><b>Date:</b></span>
                                                <span id="text-date">{{ entry.date|date:'Y-m-d' }}</span>
                                            </div>

                                            <div class="row mx-auto" id="tooltip-duration">
                                                <span><b>Duration:</b></span>
                                                <span id="text-duration">{{ entry.duration }}</span>
                                            </div>

                                            <div class="row mx-auto">
                                                <button class="tooltip-button" id="edit-button" type="button">E</button>
                                                <button class="tooltip-button" id="remove-button" type="button">R</button>
                                                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script>
        const url = "{% url 'habit_tracker:track_habit' habit %}";
    </script>
{% endblock %}